import cadquery as cq
import json
import os
import trimesh

# Load parameters
with open('revision_04/parameters.json') as f:
    params = json.load(f)

out_dir = 'revision_04/designs/P04_compact/reference_only'

def make_battery():
    # 40x30x5 pouch cell with rounded edges
    b = params['battery']
    w, l, h = b['size'][0], b['size'][1], b['size'][2]
    cx, cy, cz = b['center'][0], b['center'][1], b['z']
    
    # Main pouch
    pouch = cq.Workplane("XY").box(w, l, h).edges("|Z").fillet(2.0).edges("|X or |Y").fillet(0.5)
    
    # Top flap (folded seal)
    flap = cq.Workplane("XY").center(0, l/2).box(w - 6, 2, 0.5).translate((0, 1, h/2 - 0.25))
    pouch = pouch.union(flap)
    
    # Wires (simple cylinders protruding from flap)
    wire1 = cq.Workplane("XZ").center(-3, h/2).cylinder(10, 0.6).rotate((0,0,0), (1,0,0), 90).translate((0, l/2, 0))
    wire2 = cq.Workplane("XZ").center(3, h/2).cylinder(10, 0.6).rotate((0,0,0), (1,0,0), 90).translate((0, l/2, 0))
    
    res = pouch.union(wire1).union(wire2).translate((cx, cy, cz))
    
    cq.exporters.export(res, os.path.join(out_dir, 'battery_envelope.stl'))
    print("Exported battery_envelope.stl")

def make_xiao():
    # 21x17.8x4.2 envelope
    e = next(e for e in params['electronics'] if e['id'] == 'xiao')
    l, w, h = e['size'][0], e['size'][1], e['size'][2]
    cx, cy, cz = e['center'][0], e['center'][1], e['z']
    
    pcb = cq.Workplane("XY").box(l, w, 1.2)
    # Shield (ESP32-S3 module)
    shield = cq.Workplane("XY").center(l/2 - 8, 0).box(15, 12, 2.0).translate((0, 0, 1.6))
    # USB-C port
    usbc = cq.Workplane("XY").center(-l/2 + 3.7, 0).box(7.4, 9, 3.2).translate((0, 0, 2.2))
    # Boot/Reset buttons
    btn1 = cq.Workplane("XY").center(-l/2 + 8, w/2 - 2).box(3, 2, 1).translate((0, 0, 1.1))
    btn2 = cq.Workplane("XY").center(-l/2 + 8, -w/2 + 2).box(3, 2, 1).translate((0, 0, 1.1))
    
    res = pcb.union(shield).union(usbc).union(btn1).union(btn2).translate((cx, cy, cz))
    cq.exporters.export(res, os.path.join(out_dir, 'xiao.stl'))
    print("Exported xiao.stl")

def make_microsd():
    e = next(e for e in params['electronics'] if e['id'] == 'microsd')
    l, w, h = e['size'][0], e['size'][1], e['size'][2]
    cx, cy, cz = e['center'][0], e['center'][1], e['z']
    
    pcb = cq.Workplane("XY").box(l, w, 1.6)
    # SD Card slot
    slot = cq.Workplane("XY").center(l/2 - 7.5, 0).box(15, 14, 1.8).translate((0, 0, 1.7))
    # Header pins
    pins = cq.Workplane("XY").center(-l/2 + 1.5, 0).box(2.5, 15, 2.5).translate((0, 0, 2.05))
    
    res = pcb.union(slot).union(pins).translate((cx, cy, cz))
    cq.exporters.export(res, os.path.join(out_dir, 'microsd.stl'))
    print("Exported microsd.stl")

def make_fpc8():
    e = next(e for e in params['electronics'] if e['id'] == 'fpc8')
    l, w, h = e['size'][0], e['size'][1], e['size'][2]
    cx, cy, cz = e['center'][0], e['center'][1], e['z']
    
    pcb = cq.Workplane("XY").box(l, w, 1.6)
    # FPC Connector
    conn = cq.Workplane("XY").center(0, w/2 - 3).box(8, 4, 2.0).translate((0, 0, 1.8))
    # Header pins (assuming typical breakout)
    pins = cq.Workplane("XY").center(0, -w/2 + 2).box(20, 2.5, 2.5).translate((0, 0, 2.05))
    
    res = pcb.union(conn).union(pins).translate((cx, cy, cz))
    cq.exporters.export(res, os.path.join(out_dir, 'fpc8.stl'))
    print("Exported fpc8.stl")

def export_dac():
    # The DAC step file is ALREADY correctly translated to its assembly position 
    # (adafruit_6309_placed_VENDOR.step is the placed version generated by build.py).
    step_path = os.path.join(out_dir, 'adafruit_6309_placed_VENDOR.step')
    out_path = os.path.join(out_dir, 'dac.stl')
    try:
        shape = cq.importers.importStep(step_path)
        cq.exporters.export(shape, out_path)
        print("Exported dac.stl from placed STEP")
    except Exception as e:
        print(f"Failed to export DAC: {e}")

if __name__ == "__main__":
    make_battery()
    make_xiao()
    make_microsd()
    make_fpc8()
    export_dac()
